  - name: Install Nginx
    ansible.builtin.dnf:
      name: nginx 
      state: latest

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
  
  - name: remove default content on nginx webserver
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download and extract frontend content
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: true

  #if there is a config change, then the nginx will be restarted
  - name: copy expense.conf
    ansible.builtin.template:
      src: expense.conf.j2
      dest: /etc/nginx/default.d/expense.conf
    notify:
    - restart nginx